[package]
name = "redoubt-kernel"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
bootloader_api = "0.11"
spin = "0.9"
x86_64 = "0.15"
pic8259 = "0.11"
linked_list_allocator = "0.10"

[build-dependencies]
redoubt-initfs = { path = "../servers/initfs", artifact = "bin", target = "x86_64-unknown-none" }
redoubt-console = { path = "../servers/console", artifact = "bin", target = "x86_64-unknown-none" }

[[bin]]
name = "redoubt-kernel"
path = "src/main.rs"
test = false
